### ISSUE TITLE
AttributeError: 'Node' object has no attribute 'output_masks' 

### ISSUE THREAD

**Issue by dilipv09** [ZFTurbo/efficientnet_3D#3]
Hi @ZFTurbo ,

Thanks for sharing this amazing work. I am able to import the pretrained efficient_3D but later while setting the batchnorm layer to the inference mode by below code. Facing issue:

![image](https://user-images.githubusercontent.com/57153087/117391935-04f3b880-aebf-11eb-8b52-96d6eea08ebe.png)

Any suggestion or help would be appreciated!

Best,
Dilip

**Comment by ZFTurbo** [comment]
I googled error:
https://stackoverflow.com/questions/51821537/attributeerror-node-object-has-no-attribute-output-masks

_You're likely importing tf.keras.layers or tf.keras.applications or other keras modules from tensorflow.keras, and mixing these objects with objects from the "pure" keras package, which is not compatible, based upon version, etc._ 

Check how you import keras. `import keras from tf` or `import keras` and try to change it.

**Comment by dilipv09** [comment]
Thanks @ZFTurbo. I tried this but facing the same issue. 
I'll try again and share you if get stuck. Appreciate your input. Thanks!

**Comment by ladi-pomsar** [comment]
This can also happen if you got Keras installed in the same env you are using with tf.keras, due to the way the code in model.py is written (use keras unless exception is thrown).

**Comment by atamazian** [comment]
The question is answered, so I think this issue can be closed.
