### ISSUE TITLE
Training not starting 

### ISSUE THREAD

**Issue by sayantanbbb** [ZFTurbo/efficientnet_3D#5]
Hi, 
As a part of improving my 3d mri scan classification. 2d efficient net was just not capable for 3d  , so I used this repo. I have a average kaggle gpu  , but when I used this model with shape (50, 18,18,3) and ran model.fit , training did not start it only printed 'Epoch 1/10' even with steps_per_epoch=1 . Tried running it on a single image, with predict function still nothing pops up. This is not an computation problem as pytorch users ran it successfully without any problem, though they used grayscale image. And bigger image size. 

Help will be appreciated, 
Thank you

**Comment by innat** [comment]
@sayantanbbb,  cc. @ZFTurbo 

You can check my published notebook, particularly in the [3D modeling section](https://www.kaggle.com/ipythonx/tf-3d-2d-model-for-brain-tumor-classification/data#C.-3D-Model-:-Pre-trained-Weights) with this code. But I think it's a known issue for this 3D implementation is that it's heavy to start the training. It takes a good amount of time and it needs to be fixed.

**Comment by ZFTurbo** [comment]
It's most likely because of custom "DepthwiseConv3D" layer. I was able to run this code for training, but it was too slow for me as well.

I propose to use DenseNet121 from https://github.com/ZFTurbo/classification_models_3D

**Comment by sayantanbbb** [comment]
> It's most likely because of custom "DepthwiseConv3D" layer. I was able to run this code for training, but it was too slow for me as well.
> 
> I propose to use DenseNet121 from https://github.com/ZFTurbo/classification_models_3D

- [ ]

**Comment by sayantanbbb** [comment]
@ZFTurbo 
Thank you I will try this out  , I am currently trying to increase number of workers to speed up the training .
